### PR TITLE
Copy QR Feature

### LINKED ISSUE #86: Copy button in QR Code
It would be nice if there is a **copy button** in the QR Code modal with the download buttons
image

### PR DESCRIPTION
**Pull request by max-programming**
Closes #86

### CODE REVIEW

**Comment by max-programming** [comment]
@steven-tey Any changes required?

**Comment by steven-tey** [comment]
@max-programming sorry, haven't had time to look into this, will do soon! 🙏

**Comment by max-programming** [comment]
Sure no problem

**Review by steven-tey — APPROVED** [review]
Made some edits and it now L/FGTM!! Thanks a lot for the PR – merging now! 😄

**Pull request merged**
