### PR TITLE
Added Prettier and VSCode Config files

### PR DESCRIPTION
**Pull request by max-programming**
Continuation of #55 and #62.

Added only Prettier and VSCode **configuration files** without husky and precommit

What needs to be done:

Install prettier and import sort dep

```sh
yarn add -D prettier @trivago/prettier-plugin-sort-imports
```

### CODE REVIEW

**Comment by steven-tey** [comment]
Sweet, thank you so much for this! I'm gonna take a look at this ASAP! :)

**Comment by max-programming** [comment]
No probs. I learnt that extra work shouldn't be done if it's not asked for haha 😂

**Comment by steven-tey** [comment]
Merging this now – thank you for your PR! :)

**Comment by max-programming** [comment]
@steven-tey I am curious. Can you make changes to my fork?

**Pull request merged**
