### PR TITLE
Fix: #338

### LINKED ISSUE #338: Bug: Unexpected Padding added to the bottom of Create/Edit Link Dialog
Whenever the user tries to upload an image in the Create/Edit Link Dialog, there is some unexpected padding added to the bottom of the Dialog making the top section of the dialog unreachable and inconsistent UI.

Steps to Reproduce: 
1. Go to https://app.dub.co
2. Sign in to go to Dashboard
3. Click on 'Dub.sh Links'
4. Click on 'Create Link'
5. Toggle on 'Custom Social Media Cards'
6. Click on the section to upload an image 

https://github.com/steven-tey/dub/assets/74180320/eeb3c25a-db66-4ace-9800-d0ae5f72a271

### PR DESCRIPTION
**Pull request by prathameshjchavan**
Fixes  #338
Bug: Unexpected Padding added to the bottom of Create/Edit Link Dialog

Solution: 
- The problem was with the relative positioning of the top-most div inside the modal
- Removing the relative positioning gets rid of the initial padding of the modal
- Added relative positioning to the top-most div of each section of the form
- This way, all the absolute divs inside each section will refer to their top-most div and won't interfere with the outer divs

https://github.com/steven-tey/dub/assets/74180320/ba26f286-c93e-483c-a398-55f8274fffb0

### CODE REVIEW

**Comment by steven-tey** [comment]
Whoa this is awesome! Fixes the issue flawlessly <picture data-single-emoji=":amazing-rainbow:" title=":amazing-rainbow:">:amazing-rainbow:</picture> 

image

@prathameshjchavan do you have a GitHub Sponsors link (or any other ways to accept payment)? Would love to pay you for this amazing bug fix! 

Alternatively, thinking of using @algora-io (https://console.algora.io/) to set up bounties for Dub – thoughts? 👀

**Comment by prathameshjchavan** [comment]
> Whoa this is awesome! Fixes the issue flawlessly :amazing-rainbow:
> 
> image
> 
> @prathameshjchavan do you have a GitHub Sponsors link (or any other ways to accept payment)? Would love to pay you for this amazing bug fix!
> 
> Alternatively, thinking of using @algora-io (https://console.algora.io/) to set up bounties for Dub – thoughts? 👀

Hey Steven, Thanks for your kind words. It's great to hear that the fix worked for you!

Your willingness to support my work is truly heartwarming, and I deeply appreciate your generosity. I don't have a GitHub Sponsors link currently but, you can sponsor me here: paypal.me/prathameshchavan216. Your support means a lot to me and will help me continue my work on open source.

I also think the idea of using @algora-io to set up bounties for Dub is intriguing! It could be a great way to further incentivize contributions and improve the project.

Thanks!

**Comment by steven-tey** [comment]
Done! Thank you so much again 🙏

CleanShot 2023-09-24 at 19 45 29

**Comment by prathameshjchavan** [comment]
> Done! Thank you so much again 🙏
> 
> CleanShot 2023-09-24 at 19 45 29
> 

Thanks Steven!

**Pull request merged**
