### PR TITLE
feat: add Referrals section

### LINKED ISSUE #60: Feature Request: Traffic by source
It would be great to understand where a link is being used.

I think [simpleanalytics](https://simpleanalytics.com/simpleanalytics.com) is a good benchmark on how to show this.

image

### PR DESCRIPTION
**Pull request by Snazzah**
~~This adds [UTM parameter tracking](https://en.wikipedia.org/wiki/UTM_parameters) to links, mainly coming from [this commit](https://github.com/Snazzah/stub/commit/3a76db160296c44007f8dff2bf5eb7163d421e1a) on Stub.~~ This also adds a Referrals section to show tracked referrers.
This should work, although I haven't tested it.

closes #60

### CODE REVIEW

**Comment by steven-tey** [comment]
Oooh love this, and thanks for the headsup re: hacktoberfest, just added a `hacktoberfest` label! :) 

Also, headsup – I'm also collecting `referrer` data for all clicks so we might want to create a different section entirely – maybe SEO Stats? This could also be a separately PR :) 

Also for UTM, I'm planning to build out a UTM builder in the `app.dub.sh` UI (under `add-edit-link-modal`). Still need to think about the design for that but I'll tack that onto this PR too! :)

**Comment by Snazzah** [comment]
I saw you were also tracking the referrer in clicks, but didn't think of a good way to sort it out yet. Maybe would be good to section this under SEO stats below locations and devices. UTM builder also sounds nice, looking forward to that.

Also a note about the hacktoberfest thing, you would have to label the *repository* with `hacktoberfest` (so other devs could find it and contribute). If the repository isn't labelled, then pull requests would be labeled with `hacktoberfest-accepted` for it to count in the event.

**Comment by steven-tey** [comment]
Ohhh thanks for clarifying! Let me see how I can label the repository with `hacktoberfest`...

**Comment by Snazzah** [comment]
Yep, looks good!

**Comment by Snazzah** [comment]
I've added a "Referrals" section to the stats page to display referrers. Wanted to add it in this PR so there isn't any merge conflicts and this PR can just be for SEO-related stats.

**Comment by steven-tey** [comment]
I've been thinking about this a bit more and I don't think we're going to be storing UTM data for clicks - but rather in the link metadata itself.

A marketer can basically generate multiple short links for a given target URL based on a combination of different UTM parameters and we'd wanna store those in our DB to help them categorize those links better.

I'd still love to merge this PR but can we limit the scope to just the Referrals section? Feel free to strip out everything else!

Sorry for the confusion!

**Comment by steven-tey** [comment]
Thanks a lot for this PR @Snazzah! Merging it now! :)

**Pull request merged**
