### PR TITLE
feat: add cursor-pointer to question-circles

### LINKED ISSUE #57: padding and cursor issues on modals and tooltips
I feel like the text saying "dub.sh/github" could maybe use some margin/padding? It looks extremely weird, and kind of makes the whole spacing uneven.

image

Furthermore, @steven-tey, on tooltips -- what do you think about making the cursor change to `pointer` on hover? From what I can see, most tooltips implement this behaviour. It could be more user friendly(?). LMK, I'll be happy to work on a PR for this!

### PR DESCRIPTION
**Pull request by rwlc**
closes #57 

However, while debugging on iPad screens, I noticed that tooltips don't work. No modal pops out when you click on it. I'm not sure what the root cause of this issue is -- but I am able to reproduce this on my iPad, so there is _definitely_ some weird thing happening.

p.s - a hacktoberfest-accepted label would be great! :)

### CODE REVIEW

**Comment by rwlc** [comment]
I tried to find the root of the issue but failed, lol. @steven-tey, do you have an idea on what's going on?

**Comment by steven-tey** [comment]
@rwlc that's because I should've made the [responsive modal feature](https://twitter.com/steventey/status/1576269796475142144?s=20&t=rWhW9tao9viqEw0Qq-NYCA) I added that day work on iPad as well!

It's fine though, we can merge this for now! :)

**Comment by steven-tey** [comment]
Actually, a11y standards prefer if you use the default cursor for non-interactive tooltips: https://ux.stackexchange.com/questions/103115/tooltip-css-cursor

Reverting this for now, sorry for the trouble! I misunderstood what you meant in #57 – I thought you were talking about the tooltip for the bar charts! Apologies again! 😅

**Comment by rwlc** [comment]
Oh alright. No problem at all!!

**Pull request closed without merging**
